networks:
  falcon_net:

volumes:
  postgres_data:

services:
  falcon_ai:
    build:
      context: ./backend_src
      dockerfile: Dockerfile
    container_name: falcon_ai
    environment:
      - MCP_CYBERCHEF_URL=http://cyberchef_api:8001
      - MCP_RAG_URL=http://rag_server:8002
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@db:5432/metrics
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
    volumes:
      - ./backend_src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cyberchef_api:
        condition: service_started
      rag_server:
        condition: service_started
    networks:
      - falcon_net

  frontend:
    build:
      context: ./frontend_src
      dockerfile: Dockerfile
    container_name: falcon_frontend
    ports:
      - "3001:3001"
    # This volume mount is for development.
    volumes:
      - ./frontend_src:/app
    command: npm run dev
    depends_on:
      - falcon_ai
    networks:
      - falcon_net

  db:
    image: timescale/timescaledb:latest-pg16
    container_name: falcon_db
    environment:
      - POSTGRES_DB=metrics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - falcon_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d metrics" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rag_server:
    build:
      context: ./mcp_servers/rag_mcp_server
      dockerfile: Dockerfile
    container_name: rag_server
    volumes:
      - ./knowledge_base:/app/knowledge_base
    expose:
      - "8002"
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@db:5432/metrics
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - falcon_net
    command: ["python", "/app/src/check_and_build.py"]

  cyberchef_backend:
    build:
      context: ./mcp_servers/cyberchef_backend
      dockerfile: Dockerfile
    container_name: cyberchef_backend
    expose:
      - "3001"
    networks:
      - falcon_net

  cyberchef_api:
    build:
      context: ./mcp_servers/cyberchef_api_mcp_server
      dockerfile: Dockerfile
    container_name: cyberchef_api
    environment:
      - PYTHONUNBUFFERED=1
      - CYBERCHEF_BACKEND_URL=http://cyberchef_backend:3001
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - cyberchef_backend
    networks:
      - falcon_net