site_name: FALCON Project Documentation
site_url: http://localhost:8008/
site_author: NDJSec
site_description: >
  Technical documentation for the FALCON AI for Hardware Forensics &
  Reverse Engineering project.

nav:
  - Home: index.md
  - Architecture:
    - System Diagram: architecture/system_diagram.md
    - API Flow: architecture/api_flow.md
  - Setup Guide:
    - Local Development: setup/local_development.md
    - Running Tests: setup/testing.md

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - mermaid

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format